version: '3.9'
services:
  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - DATABASE_HOST=localhost
    ports:
      - '5432:5432'
    networks:
      - bridge

  tgbot:
    container_name: golang_container
    tty: true
    build: .
    restart: on-failure
    depends_on:
      - postgresdb
    networks:
      - bridge



networks:
  bridge: